import React, { useEffect, useState } from 'react';
import * as crmAPI from '../api/crmAPI';

const configs = {
  properties: { title: 'Properties & Inventory', fields: [['project_name','Project *'],['property_name','Property / Unit *'],['property_type','Type'],['location','Location'],['price','Price'],['status','Status'],['bedrooms','Bedrooms'],['area','Area']] },
  site_visits: { title: 'Site Visits', fields: [['lead_name','Buyer / Tenant *'],['visit_date','Visit date'],['status','Status'],['assigned','Assigned to'],['notes','Notes']] },
  bookings: { title: 'Bookings & Reservations', fields: [['lead_name','Customer *'],['token_amount','Token amount'],['booking_date','Booking date'],['status','Booking status'],['agreement_status','Agreement status']] },
  real_estate_payments: { title: 'Installments & Collections', fields: [['customer_name','Customer *'],['installment_name','Installment'],['amount_due','Amount due'],['amount_received','Amount received'],['due_date','Due date'],['received_date','Received date'],['status','Status']] },
  brokers: { title: 'Brokers & Channel Partners', fields: [['name','Broker name *'],['company','Company'],['phone','Phone'],['email','Email'],['commission_percent','Commission %'],['status','Status']] },
};
const input={width:'100%',boxSizing:'border-box',border:'1px solid #dbe4dc',borderRadius:7,padding:'9px 10px'};
export default function RealEstateWorkspace(){const [active,setActive]=useState('properties'),[items,setItems]=useState([]),[form,setForm]=useState({});const c=configs[active];const load=async()=>{const r=await crmAPI.fetchExportItems(active);setItems(r.items||[])};useEffect(()=>{setForm({});load().catch(e=>alert(e.message))},[active]);return <div style={{padding:24}}><h1 style={{margin:0,color:'#153b28'}}>Real Estate CRM</h1><p style={{color:'#64748b'}}>Property inventory, buyer enquiries, site visits and booking pipeline.</p><div style={{display:'flex',gap:8,marginBottom:16}}>{Object.entries(configs).map(([k,v])=><button key={k} onClick={()=>setActive(k)} style={{padding:'9px 13px',border:0,borderRadius:7,background:k===active?'#1a5c38':'#eaf3ed',color:k===active?'#fff':'#1a5c38',fontWeight:700}}>{v.title}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'330px 1fr',gap:18}}><form onSubmit={async e=>{e.preventDefault();await crmAPI.createExportItem(active,form);setForm({});await load()}} style={{padding:18,border:'1px solid #e5e7eb',borderRadius:10}}><h3>Add record</h3>{c.fields.map(([k,l])=><label key={k} style={{display:'block',fontSize:12,fontWeight:700,marginBottom:10}}>{l}<input required={l.includes('*')} type={k==='price'?'number':k==='visit_date'?'datetime-local':'text'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} style={{...input,marginTop:4}}/></label>)}<button style={{padding:'9px 13px',border:0,borderRadius:7,background:'#1a5c38',color:'#fff',fontWeight:700}}>Save</button></form><div style={{border:'1px solid #e5e7eb',borderRadius:10,overflow:'auto'}}><h3 style={{padding:'0 16px'}}>{c.title} ({items.length})</h3><table style={{width:'100%',borderCollapse:'collapse'}}><tbody>{items.map(x=><tr key={x.id}>{c.fields.slice(0,5).map(([k])=><td key={k} style={{padding:12,borderTop:'1px solid #e5e7eb'}}>{x[k]||'—'}</td>)}</tr>)}{!items.length&&<tr><td style={{padding:24,textAlign:'center'}}>No records yet.</td></tr>}</tbody></table></div></div></div>}
