import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Users, UserCheck, CalendarDays, WalletCards, Search, Plus, X, Clock3, Building2, Mail, Phone } from "lucide-react";
import * as api from "../api/hrmsAPI";
import "./HRMS.css";
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0), initials=n=>(n||"?").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase(), today=()=>new Date().toISOString().slice(0,10);
function Modal({title,children,onClose}){return <div className="hr-modal-backdrop" onMouseDown={onClose}><div className="hr-modal" onMouseDown={e=>e.stopPropagation()}><div className="hr-modal-head"><h2>{title}</h2><button onClick={onClose}><X size={19}/></button></div>{children}</div></div>}
function Stat({icon:Icon,label,value,note,tone}){return <div className="hr-stat"><span className={`hr-stat-icon ${tone}`}><Icon size={21}/></span><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Status({value}){return <span className={`hr-status ${(value||"").toLowerCase().replaceAll(" ","-")}`}>{value}</span>}
export default function HRMS(){
 const {pathname}=useLocation(),navigate=useNavigate(),section=pathname.split("/")[2]||"dashboard";
 const [employees,setEmployees]=useState([]),[leaves,setLeaves]=useState([]),[attendance,setAttendance]=useState([]),[payrollRows,setPayrollRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[modal,setModal]=useState(null);
 const [form,setForm]=useState({name:"",role:"",department:"Sales",email:"",phone:"",joined:today(),salary:""});
 const refresh=async()=>{setLoading(true);try{const [e,l,a,p]=await Promise.all([api.fetchEmployees(),api.fetchLeaves(),api.fetchAttendance(),api.fetchPayroll()]);setEmployees(e.employees||[]);setLeaves(l.leaves||[]);setAttendance(a.attendance||[]);setPayrollRows(p.payroll||[]);setError("")}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const filtered=useMemo(()=>employees.filter(e=>Object.values(e).join(" ").toLowerCase().includes(query.toLowerCase())),[employees,query]),present=attendance.filter(a=>["Present","Late"].includes(a.status)).length,gross=payrollRows.reduce((s,x)=>s+Number(x.gross),0),net=payrollRows.reduce((s,x)=>s+Number(x.net),0);
 const addEmployee=async e=>{e.preventDefault();try{const r=await api.createEmployee(form);setEmployees(x=>[...x,r.employee]);setModal(null);const p=await api.fetchPayroll();setPayrollRows(p.payroll||[])}catch(x){setError(x.message)}};
 const addLeave=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await api.createLeave({employeeId:Number(f.get("employeeId")),type:f.get("type"),from:f.get("from"),to:f.get("to"),reason:f.get("reason")});setLeaves(x=>[r.leave,...x]);setModal(null)}catch(x){setError(x.message)}};
 const review=async(id,status)=>{try{await api.updateLeaveStatus(id,status);setLeaves(x=>x.map(l=>l.id===id?{...l,status}:l))}catch(x){setError(x.message)}},mark=async(employeeId,status)=>{try{await api.saveAttendance({employeeId,date:today(),status,checkIn:status==="Present"?new Date().toTimeString().slice(0,5):null});const r=await api.fetchAttendance();setAttendance(r.attendance||[])}catch(x){setError(x.message)}};
 const Header=({title,subtitle,action})=><div className="hr-header"><div><div className="hr-eyebrow">Human Resource Management</div><h1>{title}</h1><p>{subtitle}</p></div>{action&&<button className="hr-primary" onClick={action}><Plus size={17}/>Add new</button>}</div>;
 let content;
 if(section==="employees")content=<><Header title="Employees" subtitle="Manage your people and employment information." action={()=>setModal("employee")}/><div className="hr-card"><div className="hr-toolbar"><div className="hr-search"><Search size={17}/><input placeholder="Search employees..." value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} employees</span></div><div className="hr-table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Contact</th><th>Joined</th><th>Status</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><div className="hr-person"><span className="hr-avatar">{initials(e.name)}</span><div><strong>{e.name}</strong><small>{e.employeeCode} · {e.role}</small></div></div></td><td>{e.department}</td><td><div className="hr-contact"><span><Mail size={13}/>{e.email}</span><span><Phone size={13}/>{e.phone||"—"}</span></div></td><td>{new Date(e.joined).toLocaleDateString("en-IN")}</td><td><Status value={e.status}/></td></tr>)}</tbody></table></div></div></>;
 else if(section==="attendance")content=<><Header title="Attendance" subtitle="Record and review today's workforce attendance."/><div className="hr-stats"><Stat icon={UserCheck} label="Present" value={present} note={`${employees.length?Math.round(present/employees.length*100):0}% attendance`} tone="green"/><Stat icon={Clock3} label="Late arrivals" value={attendance.filter(a=>a.status==="Late").length} note="After 9:30 AM" tone="amber"/><Stat icon={CalendarDays} label="Not marked" value={Math.max(0,employees.length-attendance.length)} note="Awaiting entry" tone="blue"/></div><div className="hr-card"><table><thead><tr><th>Employee</th><th>Department</th><th>Check in</th><th>Check out</th><th>Status</th><th>Action</th></tr></thead><tbody>{employees.map(e=>{const a=attendance.find(x=>Number(x.employeeId)===Number(e.id));return <tr key={e.id}><td><div className="hr-person"><span className="hr-avatar">{initials(e.name)}</span><strong>{e.name}</strong></div></td><td>{e.department}</td><td>{a?.checkIn||"—"}</td><td>{a?.checkOut||"—"}</td><td><Status value={a?.status||"Not Marked"}/></td><td><div className="hr-actions"><button onClick={()=>mark(e.id,"Present")}>Present</button><button className="reject" onClick={()=>mark(e.id,"Absent")}>Absent</button></div></td></tr>})}</tbody></table></div></>;
 else if(section==="leave")content=<><Header title="Leave management" subtitle="Review requests and track employee time off." action={()=>setModal("leave")}/><div className="hr-card"><table><thead><tr><th>Employee</th><th>Leave type</th><th>Dates</th><th>Days</th><th>Status</th><th>Action</th></tr></thead><tbody>{leaves.map(l=><tr key={l.id}><td><strong>{l.employee}</strong></td><td>{l.type}</td><td>{new Date(l.from).toLocaleDateString("en-IN")} – {new Date(l.to).toLocaleDateString("en-IN")}</td><td>{l.days}</td><td><Status value={l.status}/></td><td>{l.status==="Pending"?<div className="hr-actions"><button onClick={()=>review(l.id,"Approved")}>Approve</button><button className="reject" onClick={()=>review(l.id,"Rejected")}>Reject</button></div>:"—"}</td></tr>)}</tbody></table></div></>;
 else if(section==="payroll")content=<><Header title="Payroll" subtitle={`Monthly salary summary for ${new Date().toLocaleDateString("en-IN",{month:"long",year:"numeric"})}.`}/><div className="hr-stats"><Stat icon={WalletCards} label="Gross payroll" value={money(gross)} note={`${payrollRows.length} employees`} tone="green"/><Stat icon={WalletCards} label="Deductions" value={money(gross-net)} note="PF, ESI & tax" tone="amber"/><Stat icon={WalletCards} label="Net payable" value={money(net)} note="Current month" tone="blue"/></div><div className="hr-card"><table><thead><tr><th>Employee</th><th>Department</th><th>Gross salary</th><th>Deductions</th><th>Net salary</th><th>Status</th></tr></thead><tbody>{payrollRows.map(e=><tr key={e.id}><td><div className="hr-person"><span className="hr-avatar">{initials(e.name)}</span><div><strong>{e.name}</strong><small>{e.employeeCode}</small></div></div></td><td>{e.department}</td><td>{money(e.gross)}</td><td>{money(e.deductions)}</td><td><strong>{money(e.net)}</strong></td><td><Status value={e.status}/></td></tr>)}</tbody></table></div></>;
 else{const depts=[...new Set(employees.map(e=>e.department))];content=<><Header title="HR dashboard" subtitle="A live view of your people, attendance, and payroll."/><div className="hr-stats"><Stat icon={Users} label="Total employees" value={employees.length} note={`Across ${depts.length} departments`} tone="green"/><Stat icon={UserCheck} label="Present today" value={present} note={`${employees.length?Math.round(present/employees.length*100):0}% attendance`} tone="blue"/><Stat icon={CalendarDays} label="Pending leave" value={leaves.filter(l=>l.status==="Pending").length} note="Needs your review" tone="amber"/><Stat icon={WalletCards} label="Monthly payroll" value={money(gross)} note="Current month" tone="purple"/></div><div className="hr-grid"><div className="hr-card"><div className="hr-card-title"><div><h2>Department overview</h2><p>Current team distribution</p></div></div>{depts.map(d=><div className="hr-dept" key={d}><span className="hr-dept-icon"><Building2 size={17}/></span><div><strong>{d}</strong><small>{employees.filter(e=>e.department===d).length} employees</small></div><div className="hr-bar"><i style={{width:`${employees.length?employees.filter(e=>e.department===d).length/employees.length*100:0}%`}}/></div></div>)}</div><div className="hr-card"><div className="hr-card-title"><div><h2>Leave requests</h2><p>Latest submissions</p></div><button onClick={()=>navigate("/hrms/leave")}>View all</button></div>{leaves.slice(0,4).map(l=><div className="hr-leave-row" key={l.id}><span className="hr-avatar">{initials(l.employee)}</span><div><strong>{l.employee}</strong><small>{l.type} · {l.days} day{l.days>1?"s":""}</small></div><Status value={l.status}/></div>)}</div></div></>}
 return <div className="hr-page">{error&&<div className="hr-error">{error}<button onClick={refresh}>Retry</button></div>}{loading?<div className="hr-loading">Loading HRMS data…</div>:content}{modal==="employee"&&<Modal title="Add employee" onClose={()=>setModal(null)}><form className="hr-form" onSubmit={addEmployee}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Job title<input required value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></label><label>Department<select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}><option>Sales</option><option>Service</option><option>Finance</option><option>Operations</option><option>HR</option></select></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Joining date<input required type="date" value={form.joined} onChange={e=>setForm({...form,joined:e.target.value})}/></label><label>Monthly salary<input required min="0" type="number" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})}/></label><div className="hr-form-actions"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="hr-primary">Add employee</button></div></form></Modal>}{modal==="leave"&&<Modal title="New leave request" onClose={()=>setModal(null)}><form className="hr-form" onSubmit={addLeave}><label>Employee<select name="employeeId" required>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Leave type<select name="type"><option>Casual Leave</option><option>Sick Leave</option><option>Earned Leave</option><option>Unpaid Leave</option></select></label><label>From<input name="from" required type="date"/></label><label>To<input name="to" required type="date"/></label><label>Reason<input name="reason"/></label><div className="hr-form-actions"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="hr-primary">Submit request</button></div></form></Modal>}</div>
}
